version: '3.7'

services:

    spa:
        restart: always 
        build: ..
        container_name: spa
        image: registry.sphinx-repo.intracom-telecom.com/sphinx-project/real-time-cyber-risk-assessment/spa
        #image: spa
        ports:
            - 3001:3001
        expose:
            - 3001
        #user: root
        #priviledged: true
        working_dir: /tamarin-prover
        entrypoint: /bin/bash
        command: -c "/home/tamarin/.local/bin/tamarin-prover interactive . -i=*4"
        networks:
            - backend
            - frontend

networks:
    frontend:
        name: frontend
        driver: bridge
    backend:
        name: backend
        driver: bridge