apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\spa\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: spa
  name: spa
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: 3001-tcp
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: spa
status:
  loadBalancer: {}
