apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\spa\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: spa
  name: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spa
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mkont\PycharmProjects\spa\kompose.exe convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: spa
    spec:
      containers:
        - args:
            - -c
            - /home/tamarin/.local/bin/tamarin-prover interactive . -i=*4
          command:
            - /bin/bash
          image: registry.sphinx-repo.intracom-telecom.com/sphinx-project/real-time-cyber-risk-assessment/spa
          name: spa
          ports:
            - containerPort: 3001
          resources: {}
          workingDir: /tamarin-prover
      restartPolicy: Always
status: {}
